### ISSUE TITLE
Improved account configuration UI

### ISSUE THREAD

**Issue by zubairov** [elasticio/mssql-component#6]
Currently one have to enter an MSSQL URI as a string like:

``mssql://username:password@localhost/database``

Issues with it:
 * Not very user friendly
 * Password is visible in UI and not protected

However, advantages are that many possible settings could be build in as encoded in URI. We need t good solution to combine streights but not weaknesses.

**Comment by zubairov** [comment]
Fixed in #7

**Comment by kirill-levitskiy** [comment]
Closed #7
