### ISSUE TITLE
Outdated version of the component is on the platform

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/mssql-component#9]
There was implemented user friendly approach for configuration of a connection in PR https://github.com/elasticio/mssql-component/pull/7.

Users don't see changes, because they hadn't been deployed. These changes should be pushed to elastic.io platform.

**Comment by khanzadyan** [comment]
Version `15ecadb` was deployed to prod today 20190613.

**Comment by zubairov** [comment]
@kirill-levitskiy can this bug be closed?
